[package]
name = "hubbub-policy"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
hubbub-domain = { path = "../domain" }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
ipnet = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }

