[package]
name = "hubbub-testkit"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
hubbub-domain = { path = "../domain" }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }

